bank_ledger_project/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("balance/<str:pk>/", views.get_account_balance_by_id),
    path("transfer-funds/", views.transfer_funds),
    path("transaction/<str:pk>/", views.delete_transaction),
]

bank_ledger_project/bank_ledger_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'bank_ledger_app'


urlpatterns = [
    path('', views.index, name='index'),
    #CUSTOMER
    path('customer/profile-info/<str:pk>/', views.profile_info, name='profile-info'),
    path('customer/account-info/<str:pk>/', views.account_info, name='account-info'),
    path('customer/loan-info/<str:pk>/', views.loan_info, name='loan-info'),

    path('customer/loan/', views.loan, name='loan'),
    path('customer/pay-loan-partial/<str:pk>/', views.pay_loan_partial, name='pay-loan-partial'),
    path('customer/own-transfer/', views.own_transfer, name='own-transfer'),
    path('customer/other-transfer/', views.other_transfer, name='other-transfer'),

    # EMPLOYEE
    path('employee/customer-list-info/', views.customer_list_info, name='customer-list-info'),
    path('employee/customer-list-partial/', views.customer_list_partial, name='customer-list-partial'), 
    path('employee/customer-profile-info/<str:pk>/', views.customer_profile_info, name='customer-profile-info'),
    path('employee/customer-loan-info/<str:username>/<str:pk>/', views.customer_loan_info, name='customer-loan-info'),
    path('employee/customer-search/', views.search_customer, name='customer-search'),
    path('employee/create-customer/', views.create_customer, name='create-customer'),
    path('employee/update-customer-rank-partial/<str:pk>/', views.update_customer_rank_partial, name='update-customer-rank-partial'),
    path('employee/create-account-partial/<str:pk>/', views.create_account_partial, name='create-account-partial'),
    

    # SUPERUSER
    path('superuser/employee-list-info/', views.employee_list_info, name='employee-list-info'),
    path('superuser/create-employee/', views.create_employee, name='create-employee'),

    # API
    path('api/', include('api.urls')),

    # 2FA
    path('two_factor/profile/profile', views.profile_info_2fa, name='profile-info-2fa')


]

bank_ledger_project/bank_ledger_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('api/', include('api.urls')),
    path('', include('bank_ledger_app.urls')),
    path('accounts/', include("django.contrib.auth.urls"))
]

bank_ledger_project/bank_ledger_app/forms.py
from django import forms
from django.contrib.auth.models import User
from django.core.exceptions import ObjectDoesNotExist
from django.db import OperationalError
from .models import Employee, Customer, Account, CustomerRanks
from django.db import OperationalError


class CreateEmployeeForm(forms.ModelForm):
    email = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border"}),
        required=False)

    class Meta:
        model = User
        fields = ('email',)

    def clean(self):
        super().clean()
        return self.cleaned_data


# CUSTOMER FORMS
class LoanForm(forms.Form):
    account = forms.ModelChoiceField(
        label="from_account",
        queryset=Customer.objects.none(),
        widget=forms.Select(attrs={"class": "box box-light-border"}))

    amount = forms.DecimalField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border", "placeholder": "0.00 kr"}))

    comment = forms.CharField(
        widget=forms.TextInput(attrs={"class": "box box-light-border"}),
        required=False)


class PayLoanForm(forms.Form):
    amount = forms.DecimalField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border", "placeholder": "0.00 kr"}),
        required=True)

    recurring_payment = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "checkbox"}), 
        required=False)
    
    how_many_months = forms.DecimalField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border", "placeholder": "0"}),
        required=False)

    def clen(self):
        super().clean()
        return self.cleaned_data


class OwnTransferForm(forms.Form):
    from_account = forms.ModelChoiceField(
        label="From account",
        queryset=Customer.objects.none(),
        widget=forms.Select(attrs={"class": "box box-light-border"}))

    to_account = forms.ModelChoiceField(
        label="To account",
        queryset=Customer.objects.none(),
        widget=forms.Select(attrs={"class": "box box-light-border"}))

    amount = forms.DecimalField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border", "placeholder": "0.00 kr"}))

    comment = forms.CharField(
        widget=forms.TextInput(attrs={"class": "box box-light-border"}),
        required=False)

    def clean(self):
        super().clean()
        return self.cleaned_data


class OtherTransferForm(forms.Form):

    from_account = forms.ModelChoiceField(
        label="From account",
        queryset=Customer.objects.none(),
        widget=forms.Select(attrs={"class": "box box-light-border"}))

    to_account = forms.CharField(
        widget=forms.TextInput(attrs={"class": "box box-light-border", "placeholder": "Enter account ID"}))

    amount = forms.DecimalField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border", "placeholder": "0.00 kr"}))

    comment = forms.CharField(
        widget=forms.TextInput(attrs={"class": "box box-light-border"}),
        required=False)

    external_transfer = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "checkbox"}), 
        required=False)

    recurring_payment = forms.BooleanField(
        widget=forms.CheckboxInput(attrs={"class": "checkbox"}), 
        required=False)
    
    how_many_months = forms.DecimalField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border", "placeholder": "0"}),
        required=False)

    def clean(self):
        super().clean()
        return self.cleaned_data


# EMPLOYEE FORMS

class CreateUserForm(forms.ModelForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border"}),
        required=False)

    class Meta:
        model = User
        fields = ('username',)

    def clean(self):
        super().clean()
        return self.cleaned_data


class CreateCustomerForm(forms.ModelForm):
    email = forms.EmailField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border"}))

    phone_number = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border"}))

    class Meta:
        model = Customer
        fields = ('email', 'phone_number')

    def clean(self):
        super().clean()
        return self.cleaned_data


class UpdateCustomerRankForm(forms.Form):
    rank_options = forms.ChoiceField(
        choices=CustomerRanks.choices,
        widget=forms.Select(
            attrs={"class": "box box-light-border"}))

    def clean(self):
        super().clean()
        return self.cleaned_data


class CreateAccountForm(forms.Form):
    account_name = forms.CharField(
        widget=forms.TextInput(
            attrs={"class": "box box-light-border"}))

    def clean(self):
        super().clean()
        return self.cleaned_data


class NewCustomerForm(forms.ModelForm):
    email = forms.CharField(label='email', required=True)
    phone_number = forms.CharField(label='phone number', required=True)

    class Meta:
        model = Customer
        fields = ('email', 'phone_number',)

bank_ledger_project/bank_ledger_app/views.py
from secrets import token_urlsafe
from django.shortcuts import render, reverse, redirect
from django.contrib.auth.models import User
from .models import Employee, Customer, Account
from .forms import (
    CreateCustomerForm,
    UpdateCustomerRankForm,
    CreateAccountForm,
    LoanForm,
    OwnTransferForm,
    OtherTransferForm,
    PayLoanForm,
    CreateUserForm,
    CreateEmployeeForm,
)
from django.http import HttpResponseRedirect
from django.contrib.auth.decorators import login_required
from api.views import create_transaction


def has_customer_obj(request):
    try:
        request.user.customer
        return True
    except AttributeError:
        return False


def index(request):
    if request.user.is_superuser:
        return redirect("bank_ledger_app:create-employee")
    elif request.user.is_staff:
        return redirect("bank_ledger_app:customer-list-info")
    elif has_customer_obj(request):
        customer = request.user.customer
        return redirect("bank_ledger_app:profile-info", customer.pk)
    else:
        return redirect("two_factor:login")


###################################################
#                 CUSTOMER
###################################################
def profile_info(request, pk):
    customer = request.user.customer
    accounts = customer.all_accounts
    loans = customer.loans
    context = {
        "customer": customer,
        "accounts": accounts,
        "customer_id": pk,
        "loans": loans,
    }
    return render(request, "bank_ledger_app/customer/profile-info.html", context)


def account_info(request, pk):
    account = Account.objects.get(account_id=pk)
    account_history = account.history
    context = {"account": account, "account_history": account_history}
    return render(request, "bank_ledger_app/customer/account-info.html", context)


def loan_info(request, pk):
    loan_id = pk
    customer = request.user.customer
    customer_loans = customer.loans
    account = Account.objects.filter(customer_id=customer)
    loan_details = []
    repayments = []
    for loan in customer_loans:
        if str(loan["loan_id"]) == pk:
            loan_details.append(loan)
        for repayment in loan["repayments"]:
            repayments.append(repayment)

    context = {
        "loan_id": loan_id,
        "account_id": account,
        "loan": customer_loans,
        "loan_details": loan_details,
        "repayments": repayments,
    }
    return render(request, "bank_ledger_app/customer/loan-info.html", context)


def loan(request):
    customer: Customer = request.user.customer
    if request.method == "POST":
        form = LoanForm(request.POST)
        form.fields["account"].queryset = customer.accounts
        if form.is_valid():
            account = form.cleaned_data["account"].pk
            amount = form.cleaned_data["amount"]
            comment = form.cleaned_data["comment"]
            try:
                loan = customer.loan_money(account, amount, comment)
                if not loan.get("ok"):
                    context = {
                        "title": loan.get("title"),
                        "description": loan.get("detail"),
                    }
                    return render(
                        request, "bank_ledger_app/customer/errors.html", context
                    )
                return redirect("bank_ledger_app:profile-info", customer.pk)
            except Exception as e:
                print(e)
                return
    else:
        form = LoanForm()
    form.fields["account"].queryset = customer.accounts
    context = {
        "loan_form": form,
    }
    return render(request, "bank_ledger_app/customer/loan.html", context)


def pay_loan_partial(request, pk):
    customer: Customer = request.user.customer
    customer_loans = customer.loans
    loan_details = []
    for loan in customer_loans:
        if str(loan["loan_id"]) == pk:
            loan_details.append(loan)

    for loan_id in loan_details:
        own_account_id = loan_id["from_account"]

    form = PayLoanForm(request.POST)
    if request.method == "POST":
        if form.is_valid():
            amount = form.cleaned_data["amount"]
            try:
                if form.cleaned_data["recurring_payment"] == False:
                    loan = customer.pay_loan(own_account_id, pk, amount)
                    if not loan.get("ok"):
                        context = {
                            "title": loan.get("title"),
                            "description": loan.get("detail"),
                        }
                        return render(
                            request, "bank_ledger_app/customer/errors.html", context
                        )
                    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
                else:
                    loan = customer.pay_loan(
                        own_account_id, pk, amount, form.cleaned_data["how_many_months"]
                    )
                    if not loan.get("ok"):
                        context = {
                            "title": loan.get("title"),
                            "description": loan.get("detail"),
                        }
                        return render(
                            request, "bank_ledger_app/customer/errors.html", context
                        )
                    return HttpResponseRedirect(request.META.get("HTTP_REFERER"))
            except Exception as e:
                print(e)
                return

    pay_loan_form = PayLoanForm()
    context = {"account_id": pk, "pay_loan_form": pay_loan_form}

    return render(request, "bank_ledger_app/customer/pay-loan-partial.html", context)


def own_transfer(request):
    customer: Customer = request.user.customer
    if request.method == "POST":
        form = OwnTransferForm(request.POST)
        form.fields["from_account"].queryset = request.user.customer.accounts
        form.fields["to_account"].queryset = request.user.customer.accounts
        if form.is_valid():
            from_account = form.cleaned_data["from_account"].pk
            to_account = form.cleaned_data["to_account"].pk
            amount = form.cleaned_data["amount"]
            comment = form.cleaned_data["comment"]

            try:
                print(
                    "own_transfer trying to create transfer: ",
                    {
                        "from_account": from_account,
                        "to_account": to_account,
                        "amount": amount,
                        "comment": comment,
                    },
                )
                transfer = customer.transfer_money(
                    from_account, to_account, amount, comment
                )
                print("Transfer result is: ", transfer)
                if not transfer.get("ok"):
                    context = {
                        "title": transfer.get("title"),
                        "description": transfer.get("detail"),
                    }
                    return render(
                        request, "bank_ledger_app/customer/errors.html", context
                    )
                else:
                    return redirect("bank_ledger_app:profile-info", customer.pk)
            except Exception as e:
                print("own_transfer hit an UnknownException: ", e)
                print("*" * 30)
                return
    else:
        form = OwnTransferForm()
    form.fields["from_account"].queryset = request.user.customer.accounts
    form.fields["to_account"].queryset = request.user.customer.accounts
    context = {
        "own_transfer_form": form,
    }
    return render(request, "bank_ledger_app/customer/own-transfer.html", context)


def other_transfer(request):
    customer: Customer = request.user.customer
    if request.method == "POST":
        form = OtherTransferForm(request.POST)
        form.fields["from_account"].queryset = request.user.customer.accounts
        if form.is_valid():
            from_account = form.cleaned_data["from_account"].pk
            to_account = form.cleaned_data["to_account"]
            amount = form.cleaned_data["amount"]
            comment = form.cleaned_data["comment"]
            external_transfer = form.cleaned_data["external_transfer"]
            try:
                if form.cleaned_data["recurring_payment"] == False:
                    if external_transfer:
                        print(f"External transfer bool is: ", {external_transfer})
                        result = create_transaction(
                            own_account_id=from_account,
                            other_account_id=to_account,
                            comment=comment,
                            transfer_amount=amount,
                        )
                        print("Result of transaction is: ", result.data)
                        if not result.data.get("ok"):
                            context = {
                                "title": "Error: Insufficient funds ",
                                "description": f"Unable to transfer to money to account: {to_account}",
                            }
                            return render(
                                request, "bank_ledger_app/customer/errors.html", context
                            )

                        context = {
                            "title": "Success",
                            "description": f"You have successfully transfered {amount} to account: {to_account}",
                        }
                        return render(
                            request, "bank_ledger_app/customer/success.html", context
                        )
                    else:
                        transfer = customer.transfer_money(
                        from_account,
                        to_account,
                        amount,
                        comment,
                    )

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/account-info.html
<!-- customer/account-info.html -->

{% extends 'base.html' %}

{% block content %}
<main>
   <section class="container">
      <h1>{{ account.account_name }} History</h1>
      <div class="box-wrapper">
	 <table>
	    <tr>
	       <th>Transaction ID</th>
	       <th>Date</th>
	       <th>Time</th>
	       <th>From - account</th>
	       <th>To - account</th>
	       <th>Comment</th>
	       <th>Amount</th>
	    </tr>

	    {% for history in account_history %}
	    <tr>
	       <td>{{ history.transaction_id }}</td>
	       <td>{{ history.timestamp|date:"M d, Y" }}</td>
	       <td>{{ history.timestamp|date:"H:m" }}</td>
	       <td>{{ history.origin }}</td>
	       <td>{{ history.destination }}</td>
	       <td>{{ history.comment }}</td>
	       <td>{{ history.amount }} kr</td>
	    </tr>

	    {% endfor %}
	 </table>
      </div>
   </section>
</main>
<br><br>
<br><br>
{% endblock content %}

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/errors.html
{% extends 'base.html' %}

{% block content %}
<section class="container">
    <div class="message error">
        <h2>{{ title }}</h2>
        <p>{{ description }}</p>
        <button class="btn-error" onclick="history.back()">Go Back</button>
    </div>
</section>
{% endblock content %}

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/loan-info.html
<!-- customer/loan-info.html -->

{% extends 'base.html' %}

{% block back-button %}
<a class="btn-blue btn-back" href="{% url 'bank_ledger_app:profile-info' user.customer.pk %}"> &#x3c; Back</a>
{% endblock back-button %}
{% block content %}
<main>
	<section class="container">
		<h1>Loan info</h1>
		<div class="box-wrapper">
			<div class="box-left">
				{% for loan in loan_details %}
				<label class="label">Loan ID</label>
				<div class="box box-light-border box-left-bg">{{ loan.loan_id}}</div>
				<label class="label">Date and time</label>
				<div class="box box-light-border box-left-bg">{{ loan.date|date:"M d, Y  -  H:m" }}</div>
				<label class="label">Loaned Amount</label>
				<div class="box box-light-border box-left-bg">{{ loan.amount }}</div>
				<label class="label">Remaining Amount</label>
				<div class="box box-light-border box-left-bg">{{ loan.current_balance}} kr</div>
				<div class="btn-wrapper">
					<a 
						class="btn-blue" 	
						hx-swap="outerHTML"
						hx-get="{% url 'bank_ledger_app:pay-loan-partial' loan_id%}"
						hx-trigger="click"
						hx-target="#pay-loan"
						>Pay loan
					</a>
				</div>

				{% endfor %}
				<div id="pay-loan"></div>
			
			</div>
			<div class="box-right">
				<label class="label">Repayments history</label>
				<table>
					<tr>
						<th>From account</th>
						<th>Date</th>
						<th>Time</th>
						<th>Amount</th>	
					</tr>
					{% for repayment in repayments %}
					<tr>
						<td>{{ repayment.from_account }}</td>
						<td>{{ repayment.date|date:"M d, Y" }}</td>
						<td>{{ repayment.date|date:"H:i" }}</td>
						<td>{{ repayment.amount }} kr</td>
					</tr>	
					{% endfor %}
				</table>
				<br>	
			</div>
		</div>
	</section>

</main>
{% endblock content %}

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/loan.html
<!-- customer/loan.html-->

{% extends 'base.html' %}

{% block back-button %}
<a class="btn-blue btn-back" href="{% url 'bank_ledger_app:profile-info' user.customer.pk %}"> &#x3c; Back</a>
{% endblock back-button %}

{% block content %}
<main>
	<section class="container">
		<h1>New loan</h1>
		<div class="box-wrapper">
			<form action="{% url 'bank_ledger_app:loan' %}" method="POST" class="box-left">
				{% csrf_token %}
				{{ loan_form }}
				<div class="btn-wrapper">
					<button type="submit" class="btn-blue">New loan</button>
				</div>
			</form>
		</div>
	</section>
</main>
{% endblock content %}

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/other-transfer.html
<!-- customer/other-transfer.html-->

{% extends 'base.html'%}

{% block back-button %}
<a class="btn-blue btn-back" href="{% url 'bank_ledger_app:profile-info' user.customer.pk%}"> &#x3c; Back</a>
{% endblock back-button %}

{% block content %}
<main>
	<section class="container">
		<h1>Transfer to other Accounts</h1>
		<div class="box-wrapper">
			<div class="box-left">
				<form 
				 	method="POST"
				 	action="{% url 'bank_ledger_app:other-transfer' %}"
				 	class="box-left">
					{% csrf_token %}
					{{other_transfer_form}}
					<div class="btn-wrapper">
						<button type="submit" class="btn-blue">Transfer</button>
					</div>
				</form>
			</div>
		</div>
	</section>
</main>
{% endblock content %}

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/own-transfer.html
<!-- customer/own-transfer.html-->

{% extends 'base.html'%}

{% block back-button %}
<a class="btn-blue btn-back" href="{% url 'bank_ledger_app:profile-info' user.customer.pk %}"> &#x3c; Back</a>
{% endblock back-button %}

{% block content %}
<main>
	<section class="container">
		<h1>Transfer to own account</h1>
		<div class="box-wrapper">	
			<div class="box-left">
				<form 
				 	method="POST"
				 	action="{% url 'bank_ledger_app:own-transfer' %}"
				 	class="box-left">
					{% csrf_token %}
					{{own_transfer_form}}
					<div class="btn-wrapper">
						<button type="submit" class="btn-blue">Transfer</button>
					</div>
				</form>
			</div>
		</div>
	</section>
</main>
{% endblock content %}

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/pay-loan-partial.html
<!-- customer/payl-loan-partial.html-->

<section class="container">
  <br>
<h2 class="pay-loan">Pay loan</h2>
  <div class="box-wrapper">
    <form action="{% url 'bank_ledger_app:pay-loan-partial' account_id  %}" method="POST" class="box-left">
      {% csrf_token %}
       {{ pay_loan_form }}
      <div class="btn-wrapper">
        <button type="submit" class="btn-blue">Pay loan</button>
      </div>
    </form>
  </div>
</section>

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/profile-info.html
<!-- customer/profile-info.html -->

{% extends 'base.html' %}


{% block content %}
<main>
	<section class="container">
		<h1> Profile - {{customer.user.username}}</h1>
		<div class="box-wrapper">
			<div class="box-left">
				<label class="label">Customer id:</label>
				<div class="box box-light-border box-left-bg">{{customer.pk}}</div>
				<label class="label">Phonenumber</label>
				<div class="box box-light-border box-left-bg">{{customer.phone_number}}</div>
				<label class="label">E-mail</label>
				<div class="box box-light-border box-left-bg">{{customer.email}}</div>
				<label class="label">Rank</label>
				<div class="box box-light-border box-left-bg">{{customer.rank}}</div>
				{{ test_form }}	
			</div>
			<div class="box-right">
				<label class="label">Accounts</label>
				{% for account in accounts %}
				<a href="{% url 'bank_ledger_app:account-info' account.pk %}">
					<div class="box box-light-border box-column-2x">
						<span>{{account.account_name}}</span>
						<span>{{account.balance}} kr</span>
					</div>
				</a> 
				{% endfor %}
				<div class="btn-wrapper">
					<a class="btn-blue" href="{% url 'bank_ledger_app:own-transfer' %}">Transer to own</a>
					<a class="btn-blue btn-right" href="{% url 'bank_ledger_app:other-transfer' %}">Transer to others</a>
				</div>

				<br>
				<label class="label">{% if loans|length > 0 %}Loans{% endif%}</label>

				{% for loan in loans %}
				{% if loan.current_balance == 0 %}
				<a href="{% url 'bank_ledger_app:loan-info' loan.loan_id %}" style="display: none">
					<div class="box box-light-border box-column-2x">
						<span>{{ loan.comment|slice:"11:-1"|default:"(No name)" }}</span>
						<span>{{ loan.current_balance }} kr</span>
					</div>
				</a>
				{% else%}
				<a href="{% url 'bank_ledger_app:loan-info' loan.loan_id %}">
					<div class="box box-light-border box-column-2x">
						<span>{{ loan.comment|slice:"11:-1"|default:"(No name)" }}</span>
						<span>{{ loan.current_balance }} kr</span>
					</div>
				</a>
				{% endif %}
				{% endfor%}
			</div>
		</div>
	</section>
</main>
{% endblock content %}

bank_ledger_project/bank_ledger_app/templates/bank_ledger_app/customer/success.html
{% extends 'base.html' %}

{% block content %}
<section class="container">
    <div class="message success">
        <h2>{{ title }}</h2>
        <p>{{ description }}</p>
        <button class="btn-success" onclick="history.back()">Go Back</button>
    </div>
</section>
{% endblock content %}