bank_ledger_project/api/urls.py
from django.urls import path
from . import views

urlpatterns = [
    path("balance/<str:pk>/", views.get_account_balance_by_id),
    path("transfer-funds/", views.transfer_funds),
    path("transaction/<str:pk>/", views.delete_transaction),
]

bank_ledger_project/bank_ledger_app/urls.py
from django.urls import path, include
from . import views
from django.contrib.auth import views as auth_views

app_name = 'bank_ledger_app'


urlpatterns = [
    path('', views.index, name='index'),
    #CUSTOMER
    path('customer/profile-info/<str:pk>/', views.profile_info, name='profile-info'),
    path('customer/account-info/<str:pk>/', views.account_info, name='account-info'),
    path('customer/loan-info/<str:pk>/', views.loan_info, name='loan-info'),

    path('customer/loan/', views.loan, name='loan'),
    path('customer/pay-loan-partial/<str:pk>/', views.pay_loan_partial, name='pay-loan-partial'),
    path('customer/own-transfer/', views.own_transfer, name='own-transfer'),
    path('customer/other-transfer/', views.other_transfer, name='other-transfer'),

    # EMPLOYEE
    path('employee/customer-list-info/', views.customer_list_info, name='customer-list-info'),
    path('employee/customer-list-partial/', views.customer_list_partial, name='customer-list-partial'), 
    path('employee/customer-profile-info/<str:pk>/', views.customer_profile_info, name='customer-profile-info'),
    path('employee/customer-loan-info/<str:username>/<str:pk>/', views.customer_loan_info, name='customer-loan-info'),
    path('employee/customer-search/', views.search_customer, name='customer-search'),
    path('employee/create-customer/', views.create_customer, name='create-customer'),
    path('employee/update-customer-rank-partial/<str:pk>/', views.update_customer_rank_partial, name='update-customer-rank-partial'),
    path('employee/create-account-partial/<str:pk>/', views.create_account_partial, name='create-account-partial'),
    

    # SUPERUSER
    path('superuser/employee-list-info/', views.employee_list_info, name='employee-list-info'),
    path('superuser/create-employee/', views.create_employee, name='create-employee'),

    # API
    path('api/', include('api.urls')),

    # 2FA
    path('two_factor/profile/profile', views.profile_info_2fa, name='profile-info-2fa')


]

bank_ledger_project/bank_ledger_project/urls.py
from django.contrib import admin
from django.urls import path, include
from two_factor.urls import urlpatterns as tf_urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include(tf_urls)),
    path('api/', include('api.urls')),
    path('', include('bank_ledger_app.urls')),
    path('accounts/', include("django.contrib.auth.urls"))
]

bank_ledger_project/templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
	<head>
		<meta charset="UTF-8">
		<meta name="viewport" content="width=device-width, initial-scale=1.0">
		<title>Bank Ledger</title>
		<link rel='stylesheet' href="{% static 'css/login.css' %}">
		<link rel='stylesheet' href="{% static 'css/main.css' %}">
		{% block css %}
		{% endblock css%}
	</head>
	<body>
		<header>
			<h2>BANK LEDGER 9000</h2>
			<nav> 
				{% block navigation %}
				{% if user.is_superuser and user.is_authenticated%}
					<a class="nav-item" href="{% url 'two_factor:profile' %}">Two Factor</a>
					<a class="nav-item" href="{% url 'bank_ledger_app:create-employee' %}">Create employee</a>
					<a class="nav-item" href="{% url 'bank_ledger_app:employee-list-info' %}">employees</a>
					<a class="nav-item" href="{% url 'bank_ledger_app:customer-list-info' %}">Customers</a>
					<a class="nav-item" href="{% url 'logout' %}">logout</a>
				{% elif user.is_staff and user.is_authenticated %}
					<a class="nav-item" href="{% url 'two_factor:profile' %}">Two Factor</a>
					<a class="nav-item" href="{% url 'bank_ledger_app:create-customer' %}">Create customer</a>
					<a class="nav-item" href="{% url 'bank_ledger_app:customer-list-info' %}">Customers</a>
					<a class="nav-item" href="{% url 'logout' %}">logout</a>
				{% elif user.is_authenticated %}
					<a class="nav-item" href="{% url 'two_factor:profile' %}">Two Factor</a>
					<a class="nav-item" href="{% url 'bank_ledger_app:own-transfer' %}">Own Transfer</a>
					<a class="nav-item" href="{% url 'bank_ledger_app:other-transfer' %}">Transfer to others</a>
					<a class="nav-item" href="{% url 'bank_ledger_app:loan'%}">Take Loan</a>
					<a class="nav-item" href="{% url 'logout' %}">Log out</a>
				{% endif %}
				{% endblock navigation %}
			</nav>
		</header>
		{% block back-button %}
		{% endblock back-button %}
		{% block content %}
		{% endblock content %}
		{% block footer %}
		{% endblock footer %}






		<script src="https://unpkg.com/htmx.org@1.8.0" integrity="sha384-cZuAZ+ZbwkNRnrKi05G/fjBX+azI9DNOkNYysZ0I/X5ZFgsmMiBXgDZof30F5ofc" crossorigin="anonymous"></script>
		<script src="https://cdn.jsdelivr.net/npm/sortablejs@latest/Sortable.min.js"></script>
		<script>
			document.body.addEventListener('htmx:configRequest', (event) => {
				event.detail.headers['X-CSRFToken'] = '{{ csrf_token }}';
			})
		</script>
		<script>
			htmx.onLoad(function(content) {
				var sortables = content.querySelectorAll(".sortable");
				for (var i = 0; i < sortables.length; i++) {
					var sortable = sortables[i];
					new Sortable(sortable, {
						animation: 150,
						ghostClass: 'blue-background-class'
					});
				}
			})
		</script>

	</body>
</html>